package com.ejunior.crm_api.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;

@Entity
@Data
@Table(name = "clients")
public class Client {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @NotBlank(message = "Name is required")
  @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
  @Column(nullable = false)
  private String name;
  
  @NotBlank(message = "Email is required")
  @Email(message = "Email must be valid")
  @Column(nullable = false, unique = true)
  private String email;
  
  @Pattern(regexp = "^[\\+]?[1-9]\\d{1,14}$", message = "Phone number must be valid")
  private String contactPhone;

  // Constructors, getters, and setters can be generated by Lombok's @Data annotation

}
